version: "2"
services:
  app:
    image: nicbet/phoenix:1.5.7
    build: .
    ports:
      - "4000:4000"
    volumes:
      - ./src:/app
      - node_modules:/app/assets/node_modules
    depends_on:
      - db

  db:
    image: postgres:10
    restart: always
    volumes:
      - postgres-db:/var/lib/postgresql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

volumes:
  postgres-db:
    driver: local

  node_modules:
    driver: local
